# Generated by Django 3.0 on 2022-06-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persons',
            table='persons',
        ),
    ]
