# Generated by Django 3.0 on 2022-06-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
    ]
