# Generated by Django 3.0 on 2022-06-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220625_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='is_delete',
            field=models.SmallIntegerField(default=0),
        ),
    ]
