# Generated by Django 3.0 on 2022-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_persons_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
