# Generated by Django 3.0 on 2022-06-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_inactivep'),
    ]

    operations = [
        migrations.CreateModel(
            name='College1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('est_date', models.DateField()),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='Department1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('staff_num', models.IntegerField()),
            ],
            options={
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Princi1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('exp', models.FloatField()),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'princi',
            },
        ),
        migrations.CreateModel(
            name='Students1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Subjects1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('is_practical', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
