# Generated by Django 3.0 on 2022-06-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20220626_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='princi1',
            name='college',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.College1'),
        ),
    ]
