# Generated by Django 3.0 on 2022-06-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_princi1_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='princi1',
            name='college',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.College1'),
        ),
    ]
