# Generated by Django 3.0 on 2022-06-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_subjects1_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='City1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('CountryCode', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Population', models.IntegerField()),
            ],
            options={
                'db_table': 'city1',
            },
        ),
    ]
