# Generated by Django 3.0 on 2022-06-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_city1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department1',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depts', to='app1.College1'),
        ),
    ]
