# Generated by Django 3.0 on 2022-06-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20220626_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='students1',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studs', to='app1.Department1'),
        ),
    ]
