# Generated by Django 3.0 on 2022-06-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_car_carmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
        migrations.AlterModelTable(
            name='carmodel',
            table='carmodel',
        ),
    ]
