# Generated by Django 3.0 on 2022-07-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='private',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
